### ISSUE TITLE
show pictures with proper proportions

### ISSUE THREAD

**Issue by bjornhjelle** [Biocaching/app#25]
When showing an observation the pictures seems to be cut to fit in the window. 
It should be shown with it's proper width/height proportions.
Also applies when showing the picture of a taxon.

**Comment by pbb72** [comment]
This is the common way to show pictures in information screens on Android. I copied this from apps like Google Play Store, Google Maps (see screenshot), AirBnb, etc.

I can change this to shrinking the photo to fit the available space and display black bars to fill in, if this is preferred. But then maybe we shouldn't show the header photo in landscape mode because this would result in a tiny photo.

I'm currently working on making the header photo clickable to show it fully in full screen (as in Google Maps and AirBnb).

Portrait:
![capture _2017-03-08-21-39-13](https://cloud.githubusercontent.com/assets/1436366/23723139/55c3baf6-0448-11e7-9dc6-10cfba1a7a02.png)

Landscape:
![capture _2017-03-08-22-03-15](https://cloud.githubusercontent.com/assets/1436366/23723895/2a95060c-044b-11e7-8744-12bf1bc13e11.png)

**Comment by bjornhjelle** [comment]
Making the header photo clickable to show it fully in full screen is sufficient, at least for now.
